# Use an official OpenJDK runtime as a base image
FROM openjdk:8-jre-alpine

# Set the working directory inside the container

WORKDIR /app

# Copy the JAR file into the container at /app
COPY ./target/your-application.jar /app/your-application.jar

# Specify the command to run on container startup
CMD ["java", "-jar", "your-application.jar"]cls
