eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://192.168.59.100:30012/eureka

server:
  port: 9091

spring:
  application:
    name: service-two

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:4000/realms/myRealm
          jwk-set-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/certs


logging:
  level:
    org:
      springframework:
        security: TRACE
